// Code generated by qtc from "column_addresses.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line column_addresses.qtpl:1
package templates

//line column_addresses.qtpl:1
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line column_addresses.qtpl:1
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line column_addresses.qtpl:1
func StreamColumnAddresses(qw422016 *qt422016.Writer, input *ColumnAddressesInput) {
//line column_addresses.qtpl:1
	qw422016.N().S(`switch `)
//line column_addresses.qtpl:2
	qw422016.E().S(input.FieldName)
//line column_addresses.qtpl:2
	qw422016.N().S(` {
`)
//line column_addresses.qtpl:3
	for _, field := range input.Record.Fields {
//line column_addresses.qtpl:3
		qw422016.N().S(`    case "`)
//line column_addresses.qtpl:4
		qw422016.E().S(field.Name)
//line column_addresses.qtpl:4
		qw422016.N().S(`":
        `)
//line column_addresses.qtpl:5
		qw422016.E().S(input.TargetName)
//line column_addresses.qtpl:5
		qw422016.N().S(` = &`)
//line column_addresses.qtpl:5
		qw422016.E().S(input.RecordName)
//line column_addresses.qtpl:5
		qw422016.N().S(`.`)
//line column_addresses.qtpl:5
		qw422016.E().S(field.GoName)
//line column_addresses.qtpl:5
		qw422016.N().S(`
`)
//line column_addresses.qtpl:6
	}
//line column_addresses.qtpl:6
	qw422016.N().S(`    default:
        `)
//line column_addresses.qtpl:8
	qw422016.E().S(input.ErrName)
//line column_addresses.qtpl:8
	qw422016.N().S(` = errors.Wrap(orm.ErrFieldNotFound, `)
//line column_addresses.qtpl:8
	qw422016.E().J(input.FieldName)
//line column_addresses.qtpl:8
	qw422016.N().S(`)
}`)
//line column_addresses.qtpl:9
}

//line column_addresses.qtpl:9
func WriteColumnAddresses(qq422016 qtio422016.Writer, input *ColumnAddressesInput) {
//line column_addresses.qtpl:9
	qw422016 := qt422016.AcquireWriter(qq422016)
//line column_addresses.qtpl:9
	StreamColumnAddresses(qw422016, input)
//line column_addresses.qtpl:9
	qt422016.ReleaseWriter(qw422016)
//line column_addresses.qtpl:9
}

//line column_addresses.qtpl:9
func ColumnAddresses(input *ColumnAddressesInput) string {
//line column_addresses.qtpl:9
	qb422016 := qt422016.AcquireByteBuffer()
//line column_addresses.qtpl:9
	WriteColumnAddresses(qb422016, input)
//line column_addresses.qtpl:9
	qs422016 := string(qb422016.B)
//line column_addresses.qtpl:9
	qt422016.ReleaseByteBuffer(qb422016)
//line column_addresses.qtpl:9
	return qs422016
//line column_addresses.qtpl:9
}
