// Code generated by qtc from "connections.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line connections.qtpl:1
package templates

//line connections.qtpl:1
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line connections.qtpl:1
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line connections.qtpl:1
func StreamConnections(qw422016 *qt422016.Writer, input *ConnectionsInput) {
//line connections.qtpl:1
	qw422016.N().S(`
package `)
//line connections.qtpl:2
	qw422016.E().S(input.Package.Name)
//line connections.qtpl:2
	qw422016.N().S(`

import (
	"github.com/setare/orm"
)

type connection struct {
	*orm.Connection
}

`)
//line connections.qtpl:12
	for _, record := range input.Records {
//line connections.qtpl:12
		qw422016.N().S(`
func (conn *connection) `)
//line connections.qtpl:13
		qw422016.E().S(record.Query.Type)
//line connections.qtpl:13
		qw422016.N().S(`() *`)
//line connections.qtpl:13
		qw422016.E().S(record.Query.Type)
//line connections.qtpl:13
		qw422016.N().S(` {
	return New`)
//line connections.qtpl:14
		qw422016.E().S(record.Query.Type)
//line connections.qtpl:14
		qw422016.N().S(`(conn, `)
//line connections.qtpl:14
		qw422016.E().S(record.Schema.InternalRef)
//line connections.qtpl:14
		qw422016.N().S(`)
}
`)
//line connections.qtpl:16
	}
//line connections.qtpl:16
	qw422016.N().S(`

var DefaultConnection connection

`)
//line connections.qtpl:20
}

//line connections.qtpl:20
func WriteConnections(qq422016 qtio422016.Writer, input *ConnectionsInput) {
//line connections.qtpl:20
	qw422016 := qt422016.AcquireWriter(qq422016)
//line connections.qtpl:20
	StreamConnections(qw422016, input)
//line connections.qtpl:20
	qt422016.ReleaseWriter(qw422016)
//line connections.qtpl:20
}

//line connections.qtpl:20
func Connections(input *ConnectionsInput) string {
//line connections.qtpl:20
	qb422016 := qt422016.AcquireByteBuffer()
//line connections.qtpl:20
	WriteConnections(qb422016, input)
//line connections.qtpl:20
	qs422016 := string(qb422016.B)
//line connections.qtpl:20
	qt422016.ReleaseByteBuffer(qb422016)
//line connections.qtpl:20
	return qs422016
//line connections.qtpl:20
}
