// Code generated by qtc from "records.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line records.qtpl:1
package templates

//line records.qtpl:1
import "github.com/setare/orm/internal/document"

//line records.qtpl:3
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line records.qtpl:3
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line records.qtpl:3
func StreamRecords(qw422016 *qt422016.Writer, pkg document.Package, records []*document.Record) {
//line records.qtpl:3
	qw422016.N().S(`
package `)
//line records.qtpl:4
	qw422016.E().S(pkg.Name)
//line records.qtpl:4
	qw422016.N().S(`
`)
//line records.qtpl:6
	for _, record := range records {
//line records.qtpl:7
		for _, doc := range record.Documentation {
//line records.qtpl:7
			qw422016.N().S(`
// `)
//line records.qtpl:8
			qw422016.E().S(doc)
//line records.qtpl:9
		}
//line records.qtpl:9
		qw422016.N().S(`
type `)
//line records.qtpl:10
		qw422016.E().S(record.Name)
//line records.qtpl:10
		qw422016.N().S(` struct {
`)
//line records.qtpl:11
		for _, field := range record.Fields {
//line records.qtpl:11
			qw422016.N().S(`    `)
//line records.qtpl:12
			qw422016.E().S(field.GoName)
//line records.qtpl:12
			qw422016.N().S(` `)
//line records.qtpl:12
			qw422016.E().S(field.Type)
//line records.qtpl:12
			qw422016.N().S(`
`)
//line records.qtpl:13
		}
//line records.qtpl:13
		qw422016.N().S(`}
`)
//line records.qtpl:15
	}
//line records.qtpl:16
}

//line records.qtpl:16
func WriteRecords(qq422016 qtio422016.Writer, pkg document.Package, records []*document.Record) {
//line records.qtpl:16
	qw422016 := qt422016.AcquireWriter(qq422016)
//line records.qtpl:16
	StreamRecords(qw422016, pkg, records)
//line records.qtpl:16
	qt422016.ReleaseWriter(qw422016)
//line records.qtpl:16
}

//line records.qtpl:16
func Records(pkg document.Package, records []*document.Record) string {
//line records.qtpl:16
	qb422016 := qt422016.AcquireByteBuffer()
//line records.qtpl:16
	WriteRecords(qb422016, pkg, records)
//line records.qtpl:16
	qs422016 := string(qb422016.B)
//line records.qtpl:16
	qt422016.ReleaseByteBuffer(qb422016)
//line records.qtpl:16
	return qs422016
//line records.qtpl:16
}
