version: "3.7"
services:
  postgres:
    image: postgres:13.2-alpine
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "12345"
      POSTGRES_DB: "librarydb"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - ./.docker/postgres/data:/var/lib/postgresql/data/pgdata
    ports:
      - 5432:5432
